{{- if .Values.persistent.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "znc.fullname" . }}
  labels:
{{ include "znc.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistent.size }}
{{- end }}
