{{- $adminPassword := randAlphaNum 32 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "znc.fullname" . }}-configs
  labels:
{{ include "znc.labels" . | indent 4 }}
type: Opaque
data:
  adminPassword: {{ $adminPassword | b64enc | quote }}
stringData:
  znc.conf: |
    Version = {{ .Chart.AppVersion }}
    Skin = dark-clouds
    SSLCertFile = /znc-data/znc.pem
    SSLDHParamFile = /znc-data/znc.pem
    SSLKeyFile = /znc-data/znc.pem

    <Listener l>
      Port = {{ .Values.service.port }}
      IPv4 = {{ .Values.config.ipv4 }}
      IPv6 = {{ .Values.config.ipv6 }}
      SSL = {{ .Values.config.ssl }}
    </Listener>
    {{- range .Values.config.modules }}
    LoadModule = {{ . }}
    {{ end }}

    {{- range .Values.config.users }}
    {{- $password := randAlphaNum 32 }}
    {{- $salt := randAlphaNum 20 }}
    <User {{ .name }}>
      Admin      = {{ .admin | default false }}
      Nick       = {{ .name }}
      AltNick    = {{ .name }}_
      Ident      = {{ .name }}
      {{- range .modules }}
      LoadModule = {{ . }}
      {{- end }}

      <Pass password>
        {{- if eq .name "admin" }}
        {{- $password := $adminPassword }}
        Hash = {{ printf "%s%s" $password $salt | sha256sum }}
        {{- else }}
        Hash = {{ printf "%s%s" $password $salt | sha256sum }}
        {{- end }}
        Method = SHA256
        Salt = {{ $salt }}
      </Pass>
    </User>
    {{- end }}
